#!/usr/bin/env bash

if [ "$#" == 0 ] || [ $1 == "-h" ]; then
  printf "\n  Uses \`awk\` for quick calculations at the command line.\n\n"
  printf "    Usage:\n\t bit-calc \"(5+5)/2\"\n\n"
  exit
fi

awk "BEGIN { print $1 }"
