#!/usr/bin/env bash

version='1.6.01'
GREEN='\033[0;32m'
NC='\033[0m'

printf "\n\t\t\tBioinf Tools ${GREEN}v${version}${NC}\n"
printf "\t\tgithub.com/AstrobioMike/bioinf_tools\n\n"

printf "    If you happen to find this useful in your work and feel it is\n"
printf "    appropriate to cite this toolset, thank you :) and please do\n"
printf "    so with the following:\n\n"

printf "  Lee, M.D. Bioinformatics Tools (bit) 2018. doi:10.5281/zenodo.3633827\n\n"
