#!/usr/bin/env bash

# setting colors to use
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

if [ "$1" == "-h" ]; then
  printf "\nThis script downloads ncbi assembly summary files.\n\n"
  printf "Usage:\n\t bit-dl-ncbi-assembly-summaries\n\n"
  exit
fi


printf "\n\t\t  Downloading GenBank assembly summaries...\n\n"
curl --connect-timeout 30 --retry 10 ftp://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/assembly_summary_genbank.txt -o ncbi_assembly_info.tsv || echo "failed" > capture_any_dl_errors.tmp

  # making sure file downloaded with no errors
if [ -s capture_any_dl_errors.tmp ]; then
    printf "\n\n  ${RED}Download of NCBI assembly summaries failed :(${NC}\n  Is your internet connection weak?\n\nExiting for now.\n\n"
    rm -rf capture_any_dl_errors.tmp
    exit
else
    rm -rf capture_any_dl_errors.tmp
fi


printf "\n\n\t\t  Downloading RefSeq assembly summaries...\n\n"
curl --connect-timeout 30 --retry 10 ftp://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/assembly_summary_refseq.txt -o ncbi_RS_assembly_info.tmp || echo "failed" > capture_any_dl_errors.tmp



# making sure file downloaded with no errors
if [ -s capture_any_dl_errors.tmp ]; then
    printf "\n\n  ${RED}Download of NCBI assembly summaries failed :(${NC}\n  Is your internet connection weak?\n\nExiting for now.\n\n"
    rm -rf ${tmp_dir} ${output_dir} capture_any_dl_errors.tmp
    exit
else
    rm -rf capture_any_dl_errors.tmp
    cat ncbi_RS_assembly_info.tmp >> ncbi_assembly_info.tsv
    rm ncbi_RS_assembly_info.tmp
fi

printf "\n\t\t\t  ${GREEN}DONE!${NC}\n\n"

printf "\t\t  Stored in \"ncbi_assembly_info.tsv\".\n\n"
