#!/usr/bin/env bash

version='1.8.33'

GREEN='\033[0;32m'
NC='\033[0m'

printf "\n\t\t\tBioinf Tools ${GREEN}v${version}${NC}\n"
printf "\t\tgithub.com/AstrobioMike/bit\n\n"

printf "    If you happen to find this toolset useful in your work and feel\n"
printf "    it is appropriate to cite, thank you :) and please do\n"
printf "    so with the following:\n\n"

printf "  Lee, M.D. Bioinformatics Tools (bit) 2018. doi.org/10.5281/zenodo.4287770\n\n"

today=$(date +'%A')

printf "                                                   ${GREEN}Happy $today :)${NC}\n\n"
