#!/usr/bin/env bash

if [ "$#" == 0 ] || [ $1 == "-h" ]; then
  printf "This script returns the column names (with number) from a tab-separated file.\n\n"
  printf "Usage:\n\t bit-colnames input.tsv\n\n"
  exit
fi

if [ -f $1 ]; then
  head -n1 $1 | tr "\t" "\n" | cat -n

else
  echo -e "     ${RED}Input file not found :/${NC}" >&2
  exit 1
fi
