#!/usr/bin/env bash

# setting colors to use
GREEN='\033[0;32m'
RED='\033[0;31m'
NC='\033[0m'

if [ "$#" == 0 ] || [ $1 == "-h" ]; then
  printf "This script downloads genbank files for ncbi genomes.\n"
  printf "It needs as input the tsv produced by \"bit-parse-assembly-summary-file\".\n\n"
  printf "Usage:\n\t bit-dl-genbank-files R_insidiosa_assemblies_info.tsv\"\n\n"
  exit
fi


rm -f Failed_accessions.txt
print "\n"

while IFS=$'\t' read -r -a curr_line

do

    assembly="${curr_line[0]}"
    downloaded_accession="${curr_line[1]}"
    num=$((num+1))

    printf "\r\t On assembly: $assembly"

    # storing and building links
    base_link="${curr_line[8]}"
    end_path=$(basename $base_link)

    # attempting to download genes for assembly
    curl --silent --retry 10 -o ${assembly}.gb.gz "${base_link}/${end_path}_genomic.gbff.gz"

    if [ -s ${assembly}.gb.gz ]; then
        gunzip ${assembly}.gb.gz

    else
        
        printf "     ${RED}******************************* ${NC}NOTICE ${RED}*******************************${NC}  \n"
        printf "\t  $assembly's genbank file didn't download successfully.\n\n"
        printf "\t  Written to \"Failed_accessions.txt\".\n"
        printf "     ${RED}********************************************************************** ${NC}\n\n"

        echo ${assembly} >> Failed_accessions.txt

    fi

done < $1

printf "\n\n\t\t\t  ${GREEN}DONE!${NC}\n\n"
