#!/usr/bin/env bash

RED='\033[0;31m'
NC='\033[0m'

if [ "$#" == 0 ] || [ $1 == "-h" ]; then
  printf "This script returns the total number of bases (or amino acids) in a fasta file.\n\n"
  printf "Usage:\n\t count-bases input.fasta\n\n"
  exit
fi

if [ -f $1 ]; then
  echo $(grep -v ">" $1 | wc | awk '{print $3-$1}')

else
  echo -e "     ${RED}Input file not found :/${NC}" >&2
  exit 1
fi
