#!/usr/bin/env bash

if [ "$#" == 0 ] || [ $1 == "-h" ]; then
    printf "\n  Uses \`awk\` for quick calculations at the command line. For version\n"
    printf "  info run \`bit-version\`.\n\n"
    printf "    Usage:\n\t bit-calc \"(5+5)/2\"\n\n"
    exit
fi

awk "BEGIN { print $1 }"
