#!/usr/bin/env python

"""
coverage threshold in assembly mode is applied differently for short vs long targets (hardcoded as < 10,000 bases vs >= 10,000 bases)

    "short" ones are based on percent of subject covered by alignment based
        on blast_df["length"] / blast_df["slen"]) * 100 for individual alignments
        that surpass the percent identity threshold

    "long" ones are based on total percent of subject covered by alignment based on
        the merged regions of all alignments that surpass the percent identity threshold
"""

from bit.cli.ez_screen import main

if __name__ == "__main__":
    main()
