{% set pkg = load_setup_py_data(setup_file="../setup.py", from_recipe_dir=True) %}

package:
  name: "{{ pkg.name|lower }}"
  version: "{{ pkg.version }}"

source:
  path: ../

build:
  number: 0

requirements:
  host:
    - python>=3.10,<3.12
    - pip

  run:
    - python>=3.10,<3.12
    - biopython
    - matplotlib=3.9
    - pybedtools
    - pyfastx
    - parallel
    - scikit-bio
    - pip
    - entrez-direct
    - taxonkit
    - pandas
    - goatools
    - pigz
    - snakemake=7.26.0
    - mamba=1
    - coreutils
    - zip
    - unzip
    - pulp=2.7.0
    - numpy=1.26.4
    - blast=2
    - tqdm>=4.66.5
    - samtools
    - mosdepth
    - bwa>=0.7
    - fastp=1
    - bbmap
    - megahit=1
    - spades=4
    - rich
    - rich-argparse=1.7.1
    - pytest
    - pytest-cov

test:
  commands:
    bit-summarize-assembly -h

about:
  home: https://github.com/AstrobioMike/bit
  license: GPL3
  summary: A set of bioinformatics scripts and workflows I use regularly enough to want to have accessible from anywhere.
