###################################################################################################
## Config file for the "bit" amplicon processing workflow                                        ##
## bit: https://github.com/AstrobioMike/bit                                                      ##
##                                                                                               ##
## If you use this workflow in a publication, please consider citing :)                          ##
##   Lee M. bit: a multipurpose collection of bioinformatics tools. F1000Research 2022, 11:122.  ##
##   https://doi.org/10.12688/f1000research.79530.1                                              ##
###################################################################################################


############################################################
##################### VARIABLES TO SET #####################
############################################################

##############################################################################################################
##### This first set of variables needs to match what is on our system and/or be appropriate for our data#####
##############################################################################################################

## single-column file with unique portion of sample names
sample_info_file:
    "unique-sample-IDs.txt"

## set to "PE" for paired-end, "SE" for single-end
    # if single-end, enter appropriate info below for the "_R1_" variables and ignore the "_R2_" ones)
data_type:
    "PE"

## input reads directory (can be relative to workflow directory, or needs to be full path)
input_reads_dir:
    "test-amplicon-reads/"

## input read suffixes (region following the unique part of the sample names)
  # e.g. for paired-end data, "Sample-1_R1.fastq.gz" would be "_R1.fastq.gz" for 'input_R1_suffix' below
  # e.g. if single-end, "Sample-1.fastq.gz" would be ".fastq.gz" for 'input_R1_suffix' below, and 'input_R2_suffix' won't be used
input_R1_suffix:
    "_R1.fastq.gz"
input_R2_suffix:
    "_R2.fastq.gz"

## if we are trimming primers or not ("TRUE", or "FALSE")
trim_primers:
    "TRUE"

## primer sequences if we are trimming them (include anchoring symbols, e.g. '^', as needed, see: https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types)
F_primer:
    "^GTGCCAGCMGCCGCGGTAA"
R_primer:
    "^GGACTACHVGGGTWTCTAA"

## should cutadapt treat these as linked primers? (https://cutadapt.readthedocs.io/en/stable/recipes.html#trimming-amplicon-primers-from-paired-end-reads)
primers_linked:
    "TRUE"

## if primers are linked, we need to provide them as below, where the second half, following three periods, is the other primer reverse-complemented (see https://cutadapt.readthedocs.io/en/stable/recipes.html#trimming-amplicon-primers-from-paired-end-reads)
  # (can reverse complement while retaining ambiguous bases at this site: http://arep.med.harvard.edu/labgc/adnan/projects/Utilities/revcomp.html)
  # include anchoring symbols, e.g. '^', as needed, see: https://cutadapt.readthedocs.io/en/stable/guide.html#adapter-types
F_linked_primer:
    "^GTGCCAGCMGCCGCGGTAA...TTAGAWACCCBDGTAGTCC"
R_linked_primer:
    "^GGACTACHVGGGTWTCTAA...TTACCGCGGCKGCTGGCAC"

## discard untrimmed, sets the "--discard-untrimmed" option if TRUE
discard_untrimmed:
    "TRUE"

## target region (16S, 18S, or ITS is acceptable)
  # this determines which reference database is used for taxonomic classification
  # all are pulled from the pre-packaged DECIPHER downloads page here: http://www2.decipher.codes/Downloads.html
  # 16S uses SILVA
  # ITS uses UNITE
  # 18S uses PR2
target_region:
    "16S"

## concatenate only with dada2 instead of merging paired reads if TRUE
  # this is typically used with primers like 515-926, that captured 18S fragments that are typically too long to merge
  # note that 16S and 18S should have been separated already prior to running this workflow
  # this should likely be left as FALSE for any option other than "18S" above
concatenate_reads_only:
    "FALSE"

## values to be passed to dada2's filterAndTrim() function:
left_trunc:
    0
right_trunc:
    0
left_maxEE:
    1
right_maxEE:
    1

## minimum length threshold for cutadapt
min_cutadapt_len:
    150


######################################################################
##### The rest only need to be altered if we want to change them #####
######################################################################

## filename suffixes
primer_trimmed_R1_suffix:
    "_R1_trimmed.fastq.gz"
primer_trimmed_R2_suffix:
    "_R2_trimmed.fastq.gz"

filtered_R1_suffix:
    "_R1_filtered.fastq.gz"
filtered_R2_suffix:
    "_R2_filtered.fastq.gz"


## output prefix (if needed, e.g., to distinguish from multiple primer sets, leave as empty string if not, include connecting symbol at end if adding, e.g. "16S-")
output_prefix:
    ""

## primary workflow output directory (relative to processing directory; will be created if needed; should include the trailing "/")
outputs_dir:
    "workflow-outputs/"


############################################################
###################### GENERAL INFO ########################
############################################################
# Input reads are expected to be gzipped

## example usage command ##
# snakemake --use-conda --conda-prefix ${CONDA_PREFIX}/envs -j 2 -p

# `--use-conda` – this specifies to use the conda environments included in the workflow
# `--conda-prefix` – this allows us to point to where the needed conda environments should be stored. Including this means if we use the workflow on a different dataset somewhere else in the future, it will re-use the same conda environments rather than make new ones. The value listed here, `${CONDA_PREFIX}/envs`, is the default location for conda environments (the variable `${CONDA_PREFIX}` will be expanded to the appropriate location on whichever system it is run on).
# `-j` – this lets us set how many jobs Snakemake should run concurrently (keep in mind that many of the thread and cpu parameters set in the config.yaml file will be multiplied by this)
# `-p` – specifies to print out each command being run to the screen

# See `snakemake -h` for more options and details.
