###################################################################################################
## Snakefile for the "bit" amplicon processing workflow                                          ##
## Version 1.0.1                                                                                 ##
## bit: https://github.com/AstrobioMike/bit                                                      ##
##                                                                                               ##
## If you use this workflow in a publication, please consider citing :)                          ##
##   Lee M. bit: a multipurpose collection of bioinformatics tools. F1000Research 2022, 11:122.  ##
##   https://doi.org/10.12688/f1000research.79530.1                                              ##
###################################################################################################

import os
configfile: "config.yaml"


########################################
############# General Info #############
########################################


"""
See the corresponding 'config.yaml' file for general use information.
Variables that may need to be adjusted should be changed there, not here.
"""

########################################
#### Reading samples file into list ####
########################################

sample_IDs_file = config["sample_info_file"]
sample_ID_list = [line.strip() for line in open(sample_IDs_file)]

# making sure there are all unique names
if len(set(sample_ID_list)) != len(sample_ID_list):

    print("\n    Not all sample IDs in the " + str(config["sample_info_file"]) + " file are unique :(\n")
    print("    Exiting for now.\n")
    exit(1)

########################################
######## Setting up directories ########
########################################

input_reads_dir = config["input_reads_dir"]
fastqc_out_dir = config["outputs_dir"] + "fastqc-outputs/"
trimmed_reads_dir = config["outputs_dir"] + "trimmed-reads/"
filtered_reads_dir = config["outputs_dir"] + "filtered-reads/"
final_outputs_dir = config["outputs_dir"] + "final-outputs/"
benchmarks_dir = "benchmarks/"

if config["trim_primers"] == "TRUE":
    needed_dirs = [fastqc_out_dir, trimmed_reads_dir, filtered_reads_dir, final_outputs_dir, benchmarks_dir]
else:
    needed_dirs = [fastqc_out_dir, filtered_reads_dir, final_outputs_dir, benchmarks_dir]

for dir in needed_dirs:
    try:
        os.mkdir(dir)
    except:
        pass


########################################
############# Rules start ##############
########################################

#### rules if paired-end data ####
if config["data_type"] == "PE":

    # "all" starting rule for paired-end data
    if config["trim_primers"] == "TRUE":

        rule all:
            input:
                expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"], ID = sample_ID_list),
                expand(filtered_reads_dir + "{ID}" + config["filtered_R2_suffix"], ID = sample_ID_list),
                expand(trimmed_reads_dir + "{ID}" + config["primer_trimmed_R1_suffix"], ID = sample_ID_list),
                expand(trimmed_reads_dir + "{ID}" + config["primer_trimmed_R2_suffix"], ID = sample_ID_list),
                trimmed_reads_dir + config["output_prefix"] + "cutadapt.log",
                trimmed_reads_dir + config["output_prefix"] + "trimmed-read-counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.biom",
                final_outputs_dir + config["output_prefix"] + "ASVs.fasta",
                final_outputs_dir + config["output_prefix"] + "read-count-tracking.tsv",
                final_outputs_dir + config["output_prefix"] + "counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.tsv",
                fastqc_out_dir + config["output_prefix"] + "raw_multiqc_report.zip",
                fastqc_out_dir + config["output_prefix"] + "filtered_multiqc_report.zip"
            shell:
                """
                bash scripts/combine-benchmarks.sh
                """

    # if we are not trimming the primers
    else:

        rule all:
            input:
                expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"], ID = sample_ID_list),
                expand(filtered_reads_dir + "{ID}" + config["filtered_R2_suffix"], ID = sample_ID_list),
                final_outputs_dir + config["output_prefix"] + "taxonomy.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.biom.zip",
                final_outputs_dir + config["output_prefix"] + "ASVs.fasta",
                final_outputs_dir + config["output_prefix"] + "read-count-tracking.tsv",
                final_outputs_dir + config["output_prefix"] + "counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.tsv",
                fastqc_out_dir + config["output_prefix"] + "raw_multiqc_report.zip",
                fastqc_out_dir + config["output_prefix"] + "filtered_multiqc_report.zip"
            shell:
                """
                bash scripts/combine-benchmarks.sh
                """


    # R processing rule for paired-end data
    if config["trim_primers"] == "TRUE":

        rule run_R_PE:
            conda:
                "envs/R.yaml"
            input:
                expand(trimmed_reads_dir + "{ID}" + config["primer_trimmed_R1_suffix"], ID = sample_ID_list),
                expand(trimmed_reads_dir + "{ID}" + config["primer_trimmed_R2_suffix"], ID = sample_ID_list),
                trimmed_reads_dir + config["output_prefix"] + "trimmed-read-counts.tsv"
            output:
                expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"], ID = sample_ID_list),
                expand(filtered_reads_dir + "{ID}" + config["filtered_R2_suffix"], ID = sample_ID_list),
                final_outputs_dir + config["output_prefix"] + "taxonomy.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.biom",
                final_outputs_dir + config["output_prefix"] + "ASVs.fasta",
                final_outputs_dir + config["output_prefix"] + "read-count-tracking.tsv",
                final_outputs_dir + config["output_prefix"] + "counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.tsv"
            params:
                left_trunc = config["left_trunc"],
                right_trunc = config["right_trunc"],
                left_maxEE = config["left_maxEE"],
                right_maxEE = config["right_maxEE"],
                trim_primers = config["trim_primers"],
                trimmed_reads_dir = trimmed_reads_dir,
                filtered_reads_dir = filtered_reads_dir,
                primer_trimmed_R1_suffix = config["primer_trimmed_R1_suffix"],
                primer_trimmed_R2_suffix = config["primer_trimmed_R2_suffix"],
                filtered_R1_suffix = config["filtered_R1_suffix"],
                filtered_R2_suffix = config["filtered_R2_suffix"],
                final_outputs_dir = final_outputs_dir,
                target_region = config["target_region"],
                output_prefix = config["output_prefix"],
                concatenate_reads_only = config["concatenate_reads_only"]
            resources:
                mem_mb = 200000,
                cpus = 10
            log:
                "R-processing.log"
            benchmark:
                benchmarks_dir + "run_R-benchmarks.tsv"
            shell:
                """
                Rscript scripts/Illumina-PE-R-processing.R "{params.left_trunc}" "{params.right_trunc}" "{params.left_maxEE}" "{params.right_maxEE}" "{params.trim_primers}" "{sample_IDs_file}" "{params.trimmed_reads_dir}" "{params.filtered_reads_dir}" "{params.primer_trimmed_R1_suffix}" "{params.primer_trimmed_R2_suffix}" "{params.filtered_R1_suffix}" "{params.filtered_R2_suffix}" "{params.final_outputs_dir}" "{params.output_prefix}" "{params.target_region}" "{params.concatenate_reads_only}" > {log} 2>&1
                """

    # if we did not trim the primers
    else:

        rule run_R_PE:
            conda:
                "envs/R.yaml"
            input:
                expand(input_reads_dir + "{ID}" + config["input_R1_suffix"], ID = sample_ID_list),
                expand(input_reads_dir + "{ID}" + config["input_R2_suffix"], ID = sample_ID_list)
            output:
                expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"], ID = sample_ID_list),
                expand(filtered_reads_dir + "{ID}" + config["filtered_R2_suffix"], ID = sample_ID_list),
                final_outputs_dir + config["output_prefix"] + "taxonomy.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.biom",
                final_outputs_dir + config["output_prefix"] + "ASVs.fasta",
                final_outputs_dir + config["output_prefix"] + "read-count-tracking.tsv",
                final_outputs_dir + config["output_prefix"] + "counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.tsv"
            params:
                left_trunc = config["left_trunc"],
                right_trunc = config["right_trunc"],
                left_maxEE = config["left_maxEE"],
                right_maxEE = config["right_maxEE"],
                trim_primers = config["trim_primers"],
                input_reads_dir = input_reads_dir,
                filtered_reads_dir = filtered_reads_dir,
                input_R1_suffix = config["input_R1_suffix"],
                input_R2_suffix = config["input_R2_suffix"],
                filtered_R1_suffix = config["filtered_R1_suffix"],
                filtered_R2_suffix = config["filtered_R2_suffix"],
                final_outputs_dir = final_outputs_dir,
                target_region = config["target_region"],
                output_prefix = config["output_prefix"],
                concatenate_reads_only = config["concatenate_reads_only"]
            resources:
                mem_mb = 200000,
                cpus = 10
            log:
                "R-processing.log"
            benchmark:
                benchmarks_dir + "run_R-benchmarks.tsv"
            shell:
                """
                Rscript scripts/Illumina-PE-R-processing.R "{params.left_trunc}" "{params.right_trunc}" "{params.left_maxEE}" "{params.right_maxEE}" "{params.trim_primers}" "{sample_IDs_file}" "{params.input_reads_dir}" "{params.filtered_reads_dir}" "{params.input_R1_suffix}" "{params.input_R2_suffix}" "{params.filtered_R1_suffix}" "{params.filtered_R2_suffix}" "{params.final_outputs_dir}" "{params.output_prefix}" "{params.target_region}" "{params.concatenate_reads_only}" > {log} 2>&1
                """


    # cutadapt rule for paired-end data
    rule cutadapt_PE:
        """ this rule runs cutadapt. It is only executed if config["trim_primers"] is "TRUE" """
        conda:
            "envs/cutadapt.yaml"
        input:
            R1 = input_reads_dir + "{ID}" + config["input_R1_suffix"],
            R2 = input_reads_dir + "{ID}" + config["input_R2_suffix"]
        output:
            R1 = trimmed_reads_dir + "{ID}" + config["primer_trimmed_R1_suffix"],
            R2 = trimmed_reads_dir + "{ID}" + config["primer_trimmed_R2_suffix"],
            log = trimmed_reads_dir + "{ID}-cutadapt.log",
            trim_counts = trimmed_reads_dir + "{ID}-trimmed-counts.tsv"
        params:
            F_linked_primer = config["F_linked_primer"],
            R_linked_primer = config["R_linked_primer"],
            F_primer = config["F_primer"],
            R_primer = config["R_primer"],
            min_cutadapt_len = config["min_cutadapt_len"],
            primers_linked = config["primers_linked"],
            discard_untrimmed = config["discard_untrimmed"]
        log:
            trimmed_reads_dir + "{ID}-cutadapt.log"
        benchmark:
            benchmarks_dir + "cutadapt-{ID}-benchmarks.tsv"
        shell:
            """
            # command depends on if primers are linked or not
            if [ {params.primers_linked} == "TRUE" ]; then

                if [ {params.discard_untrimmed} == "TRUE" ]; then
                    cutadapt -a {params.F_linked_primer} -A {params.R_linked_primer} -o {output.R1} -p {output.R2} --discard-untrimmed -m {params.min_cutadapt_len} {input.R1} {input.R2} > {log} 2>&1
                else
                    cutadapt -a {params.F_linked_primer} -A {params.R_linked_primer} -o {output.R1} -p {output.R2} -m {params.min_cutadapt_len} {input.R1} {input.R2} > {log} 2>&1
                fi

            else

                if [ {params.discard_untrimmed} == "TRUE" ]; then
                    cutadapt -g {params.F_primer} -G {params.R_primer} -o {output.R1} -p {output.R2} --discard-untrimmed -m {params.min_cutadapt_len} {input.R1} {input.R2} > {log} 2>&1
                else
                    cutadapt -g {params.F_primer} -G {params.R_primer} -o {output.R1} -p {output.R2} -m {params.min_cutadapt_len} {input.R1} {input.R2} > {log} 2>&1
                fi

            fi

            paste <( printf "{wildcards.ID}" ) <( grep "read pairs processed" {output.log} | tr -s " " "\t" | cut -f 5 | tr -d "," ) <( grep "Pairs written" {output.log} | tr -s " " "\t" | cut -f 5 | tr -d "," ) > {output.trim_counts}
            """

    # rule for raw fastqc for paired-end data
    rule raw_fastqc_PE:
        """
        This rule runs fastqc on all raw input fastq files.
        """

        conda:
            "envs/qc.yaml"
        input:
            input_reads_dir + "{ID}" + config["input_R1_suffix"],
            input_reads_dir + "{ID}" + config["input_R2_suffix"]
        output:
            input_reads_dir + "{ID}" + config["input_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.zip",
            input_reads_dir + "{ID}" + config["input_R2_suffix"].rsplit(".", 2)[0] + "_fastqc.zip"
        benchmark:
            benchmarks_dir + "raw_fastqc-{ID}-benchmarks.tsv"
        shell:
            """
            fastqc {input} -t 2 -q
            """

    # rule for raw multiqc for paired-end data
    rule raw_multiqc_PE:
        """
        This rule collates all raw fastqc outputs.
        """

        conda:
            "envs/qc.yaml"
        input:
            expand(input_reads_dir + "{ID}" + config["input_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.zip", ID = sample_ID_list),
            expand(input_reads_dir + "{ID}" + config["input_R2_suffix"].rsplit(".", 2)[0] + "_fastqc.zip", ID = sample_ID_list)
        params:
            int_out_dir = config["output_prefix"] + "raw_multiqc_report",
            out_filename_prefix = config["output_prefix"] + "raw_multiqc",
            int_out_data_dir = config["output_prefix"] + "raw_multiqc_data",
            int_html_file = config["output_prefix"] + "raw_multiqc.html",
            int_zip = config["output_prefix"] + "raw_multiqc_report.zip",
            r1_html_files = expand(input_reads_dir + "{ID}" + config["input_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.html", ID = sample_ID_list),
            r2_html_files = expand(input_reads_dir + "{ID}" + config["input_R2_suffix"].rsplit(".", 2)[0] + "_fastqc.html", ID = sample_ID_list),
            config_file = "config/multiqc.config"
        output:
            final_out_zip = fastqc_out_dir + config["output_prefix"] + "raw_multiqc_report.zip"
        benchmark:
            benchmarks_dir + "raw_multiqc-benchmarks.tsv"
        shell:
            """
            multiqc -q -n {params.out_filename_prefix} --force --cl-config 'max_table_rows: 99999999' --interactive --config {params.config_file} {input} > /dev/null 2>&1
            
            # removing the individual fastqc files
            rm -rf {input} {params.r1_html_files} {params.r2_html_files}

            # making an output report directory and moving things into it
            mkdir -p {params.int_out_dir}
            mv {params.int_html_file} {params.int_out_data_dir} {params.int_out_dir}
            
            # zipping and removing unzipped dir
            zip -q -r {params.int_zip} {params.int_out_dir} && rm -rf {params.int_out_dir}

            # moving to final wanted location
            mv {params.int_zip} {output.final_out_zip}
            """


    # rule for filtered fastqc for paired-end data (inherits from rule raw_fastqc_PE)
    use rule raw_fastqc_PE as filtered_fastqc_PE with:
        input:
            filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"],
            filtered_reads_dir + "{ID}" + config["filtered_R2_suffix"]
        output:
            filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.zip",
            filtered_reads_dir + "{ID}" + config["filtered_R2_suffix"].rsplit(".", 2)[0] + "_fastqc.zip"
        benchmark:
            benchmarks_dir + "filtered_fastqc-{ID}-benchmarks.tsv"


    # rule for filtered multiqc for paired-end data (inherits from raw_multiqc_PE)
    use rule raw_multiqc_PE as filtered_multiqc_PE with:
        input:
            expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.zip", ID = sample_ID_list),
            expand(filtered_reads_dir + "{ID}" + config["filtered_R2_suffix"].rsplit(".", 2)[0] + "_fastqc.zip", ID = sample_ID_list)
        params:
            int_out_dir = config["output_prefix"] + "filtered_multiqc_report",
            out_filename_prefix = config["output_prefix"] + "filtered_multiqc",
            int_out_data_dir = config["output_prefix"] + "filtered_multiqc_data",
            int_html_file = config["output_prefix"] + "filtered_multiqc.html",
            int_zip = config["output_prefix"] + "filtered_multiqc_report.zip",
            r1_html_files = expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.html", ID = sample_ID_list),
            r2_html_files = expand(filtered_reads_dir + "{ID}" + config["filtered_R2_suffix"].rsplit(".", 2)[0] + "_fastqc.html", ID = sample_ID_list),
            config_file = "config/multiqc.config"
        output:
            final_out_zip = fastqc_out_dir + config["output_prefix"] + "filtered_multiqc_report.zip"
        benchmark:
            benchmarks_dir + "filtered_multiqc-benchmarks.tsv"



#### end of rules specific for paired-end data ####

##################################
#### rules if single-end data ####
##################################
if config["data_type"] == "SE":

    # "all" starting rule for single-end data
    if config["trim_primers"] == "TRUE":

        rule all:
            input:
                expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"], ID = sample_ID_list),
                expand(trimmed_reads_dir + "{ID}" + config["primer_trimmed_R1_suffix"], ID = sample_ID_list),
                trimmed_reads_dir + config["output_prefix"] + "cutadapt.log",
                trimmed_reads_dir + config["output_prefix"] + "trimmed-read-counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.biom.zip",
                final_outputs_dir + config["output_prefix"] + "ASVs.fasta",
                final_outputs_dir + config["output_prefix"] + "read-count-tracking.tsv",
                final_outputs_dir + config["output_prefix"] + "counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.tsv",
                fastqc_out_dir + config["output_prefix"] + "raw_multiqc_report.zip",
                fastqc_out_dir + config["output_prefix"] + "filtered_multiqc_report.zip"
            shell:
                """
                bash scripts/combine-benchmarks.sh
                """

    # if we are not trimming the primers
    else:

        rule all:
            input:
                expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"], ID = sample_ID_list),
                final_outputs_dir + config["output_prefix"] + "taxonomy.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.biom.zip",
                final_outputs_dir + config["output_prefix"] + "ASVs.fasta",
                final_outputs_dir + config["output_prefix"] + "read-count-tracking.tsv",
                final_outputs_dir + config["output_prefix"] + "counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.tsv",
                fastqc_out_dir + config["output_prefix"] + "raw_multiqc_report.zip",
                fastqc_out_dir + config["output_prefix"] + "filtered_multiqc_report.zip"
            shell:
                """
                bash scripts/combine-benchmarks.sh
                """


    # R processing rule for single-end data
    if config["trim_primers"] == "TRUE":

        rule run_R_SE:
            conda:
                "envs/R.yaml"
            input:
                expand(trimmed_reads_dir + "{ID}" + config["primer_trimmed_R1_suffix"], ID = sample_ID_list),
                trimmed_reads_dir + config["output_prefix"] + "trimmed-read-counts.tsv"
            output:
                expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"], ID = sample_ID_list),
                final_outputs_dir + config["output_prefix"] + "taxonomy.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.biom",
                final_outputs_dir + config["output_prefix"] + "ASVs.fasta",
                final_outputs_dir + config["output_prefix"] + "read-count-tracking.tsv",
                final_outputs_dir + config["output_prefix"] + "counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.tsv"
            params:
                left_trunc = config["left_trunc"],
                left_maxEE = config["left_maxEE"],
                trim_primers = config["trim_primers"],
                trimmed_reads_dir = trimmed_reads_dir,
                filtered_reads_dir = filtered_reads_dir,
                primer_trimmed_R1_suffix = config["primer_trimmed_R1_suffix"],
                filtered_R1_suffix = config["filtered_R1_suffix"],
                final_outputs_dir = final_outputs_dir,
                target_region = config["target_region"],
                output_prefix = config["output_prefix"]
            resources:
                mem_mb = 200000,
                cpus = 10
            log:
                "R-processing.log"
            benchmark:
                benchmarks_dir + "run_R-benchmarks.tsv"
            shell:
                """
                Rscript scripts/Illumina-SE-R-processing.R "{params.left_trunc}" "{params.left_maxEE}" "{params.trim_primers}" "{sample_IDs_file}" "{params.trimmed_reads_dir}" "{params.filtered_reads_dir}" "{params.primer_trimmed_R1_suffix}" "{params.filtered_R1_suffix}" "{params.final_outputs_dir}" "{params.output_prefix}" "{params.target_region}" > {log} 2>&1
                """

    # if we did not trim the primers
    else:

        rule run_R_SE:
            conda:
                "envs/R.yaml"
            input:
                expand(input_reads_dir + "{ID}" + config["input_R1_suffix"], ID = sample_ID_list)
            output:
                expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"], ID = sample_ID_list),
                final_outputs_dir + config["output_prefix"] + "taxonomy.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.biom",
                final_outputs_dir + config["output_prefix"] + "ASVs.fasta",
                final_outputs_dir + config["output_prefix"] + "read-count-tracking.tsv",
                final_outputs_dir + config["output_prefix"] + "counts.tsv",
                final_outputs_dir + config["output_prefix"] + "taxonomy-and-counts.tsv"
            params:
                left_trunc = config["left_trunc"],
                left_maxEE = config["left_maxEE"],
                trim_primers = config["trim_primers"],
                input_reads_dir = input_reads_dir,
                filtered_reads_dir = filtered_reads_dir,
                input_R1_suffix = config["input_R1_suffix"],
                filtered_R1_suffix = config["filtered_R1_suffix"],
                final_outputs_dir = final_outputs_dir,
                target_region = config["target_region"],
                output_prefix = config["output_prefix"]
            resources:
                mem_mb = 200000,
                cpus = 10
            log:
                "R-processing.log"
            benchmark:
                benchmarks_dir + "run_R-benchmarks.tsv"
            shell:
                """
                Rscript scripts/Illumina-SE-R-processing.R "{params.left_trunc}" "{params.left_maxEE}" "{params.trim_primers}" "{sample_IDs_file}" "{params.input_reads_dir}" "{params.filtered_reads_dir}" "{params.input_R1_suffix}" "{params.filtered_R1_suffix}" "{params.final_outputs_dir}" "{params.output_prefix}" "{params.target_region}" > {log} 2>&1
                """


    # cutadapt rule for single-end data
    rule cutadapt_SE:
        """ this rule runs cutadapt. It is only executed if config["trim_primers"] is "TRUE" """
        conda:
            "envs/cutadapt.yaml"
        input:
            R1 = input_reads_dir + "{ID}" + config["input_R1_suffix"]
        output:
            R1 = trimmed_reads_dir + "{ID}" + config["primer_trimmed_R1_suffix"],
            log = trimmed_reads_dir + "{ID}-cutadapt.log",
            trim_counts = trimmed_reads_dir + "{ID}-trimmed-counts.tsv"
        params:
            F_linked_primer = config["F_linked_primer"],
            F_primer = config["F_primer"],
            min_cutadapt_len = config["min_cutadapt_len"],
            primers_linked = config["primers_linked"],
            discard_untrimmed = config["discard_untrimmed"]
        log:
            trimmed_reads_dir + "{ID}-cutadapt.log"
        benchmark:
            benchmarks_dir + "cutadapt-{ID}-benchmarks.tsv"
        shell:
            """
            # command depends on if primers are linked or not
            if [ {params.primers_linked} == "TRUE" ]; then

                if [ {params.discard_untrimmed} == "TRUE" ]; then
                    cutadapt -a {params.F_linked_primer} -o {output.R1} --discard-untrimmed -m {params.min_cutadapt_len} {input.R1} > {log} 2>&1
                else
                    cutadapt -a {params.F_linked_primer} -o {output.R1} -m {params.min_cutadapt_len} {input.R1} > {log} 2>&1
                fi

            else

                if [ {params.discard_untrimmed} == "TRUE" ]; then
                    cutadapt -g {params.F_primer} -o {output.R1} --discard-untrimmed -m {params.min_cutadapt_len} {input.R1} > {log} 2>&1
                else
                    cutadapt -g {params.F_primer} -o {output.R1} -m {params.min_cutadapt_len} {input.R1} > {log} 2>&1
                fi

            fi

            paste <( printf "{wildcards.ID}" ) <( grep "reads processed" {output.log} | tr -s " " "\t" | cut -f 4 | tr -d "," ) <( grep "Reads written" {output.log} | tr -s " " "\t" | cut -f 5 | tr -d "," ) > {output.trim_counts}
            """


    # rule for raw fastqc for single-end data
    rule raw_fastqc_SE:
        """
        This rule runs fastqc on all raw input fastq files.
        """

        conda:
            "envs/qc.yaml"
        input:
            input_reads_dir + "{ID}" + config["input_R1_suffix"]
        output:
            input_reads_dir + "{ID}" + config["input_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.zip"
        benchmark:
            benchmarks_dir + "raw_fastqc-{ID}-benchmarks.tsv"
        shell:
            """
            fastqc {input} -t 1 -q
            """


    # rule for raw multiqc for single-end data
    rule raw_multiqc_SE:
        """
        This rule collates all raw fastqc outputs.
        """

        conda:
            "envs/qc.yaml"
        input:
            expand(input_reads_dir + "{ID}" + config["input_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.zip", ID = sample_ID_list)
        params:
            int_out_dir = config["output_prefix"] + "raw_multiqc_report",
            out_filename_prefix = config["output_prefix"] + "raw_multiqc",
            int_out_data_dir = config["output_prefix"] + "raw_multiqc_data",
            int_html_file = config["output_prefix"] + "raw_multiqc.html",
            int_zip = config["output_prefix"] + "raw_multiqc_report.zip",
            r1_html_files = expand(input_reads_dir + "{ID}" + config["input_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.html", ID = sample_ID_list),
            config_file = "config/multiqc.config"
        output:
            final_out_zip = fastqc_out_dir + config["output_prefix"] + "raw_multiqc_report.zip"
        benchmark:
            benchmarks_dir + "raw_multiqc-benchmarks.tsv"
        shell:
            """
            multiqc -q -n {params.out_filename_prefix} --force --cl-config 'max_table_rows: 99999999' --interactive --config {params.config_file} {input} > /dev/null 2>&1

            # removing the individual fastqc files
            rm -rf {input} {params.r1_html_files}

            # making an output report directory and moving things into it
            mkdir -p {params.int_out_dir}
            mv {params.int_html_file} {params.int_out_data_dir} {params.int_out_dir}

            # zipping and removing unzipped dir
            zip -q -r {params.int_zip} {params.int_out_dir} && rm -rf {params.int_out_dir}

            # moving to final wanted location
            mv {params.int_zip} {output.final_out_zip}
            """


    # rule for filtered fastqc for single-end data (inherits from rule raw_fastqc_SE)
    use rule raw_fastqc_SE as filtered_fastqc_SE with:
        input:
            filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"]
        output:
            filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.zip"
        benchmark:
            benchmarks_dir + "filtered_fastqc-{ID}-benchmarks.tsv"


    # rule for filtered multiqc for single-end data (inherits from rule raw_multiqc_SE)
    use rule raw_multiqc_SE as filtered_multiqc_SE with:
        input:
            expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.zip", ID = sample_ID_list)
        params:
            int_out_dir = config["output_prefix"] + "filtered_multiqc_report",
            out_filename_prefix = config["output_prefix"] + "filtered_multiqc",
            int_out_data_dir = config["output_prefix"] + "filtered_multiqc_data",
            int_html_file = config["output_prefix"] + "filtered_multiqc.html",
            int_zip = config["output_prefix"] + "filtered_multiqc_report.zip",
            r1_html_files = expand(filtered_reads_dir + "{ID}" + config["filtered_R1_suffix"].rsplit(".", 2)[0] + "_fastqc.html", ID = sample_ID_list),
            config_file = "config/multiqc.config"
        output:
            final_out_zip = fastqc_out_dir + config["output_prefix"] + "filtered_multiqc_report.zip"
        benchmark:
            benchmarks_dir + "filtered_multiqc-benchmarks.tsv"


#### end of rules specific for single-end data ####

##################################################################
#### rules that are the same whether paired-end or single-end ####
##################################################################
rule combine_cutadapt_logs_and_summarize:
    """ this rule combines the cutadapt logs and summarizes them. It is only executed if config["trim_primers"] is "TRUE" """
    input:
        counts = expand(trimmed_reads_dir + "{ID}-trimmed-counts.tsv", ID = sample_ID_list),
        logs = expand(trimmed_reads_dir + "{ID}-cutadapt.log", ID = sample_ID_list)
    output:
        combined_log = trimmed_reads_dir + config["output_prefix"] + "cutadapt.log",
        combined_counts = trimmed_reads_dir + config["output_prefix"] + "trimmed-read-counts.tsv"
    benchmark:
        benchmarks_dir + "combine_cutadapt_logs_and_summarize-benchmarks.tsv"
    shell:
        """
        cat {input.logs} > {output.combined_log}
        rm {input.logs}
        
        cat <( printf "sample\traw_reads\tcutadapt_trimmed\n" ) <( cat {input.counts} ) > {output.combined_counts}
        rm {input.counts}
        """


rule clean_all:
    shell:
        "rm -rf {needed_dirs}"
