name: build-and-test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    if: ${{ !contains(github.event.head_commit.message, '[skip-ci]') }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-15-intel"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v5

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v4
      with:
        architecture: "x86_64"
        channels: conda-forge,bioconda
        channel-priority: strict
        conda-remove-defaults: true
        auto-update-conda: true

    - name: Build conda package
      run: |
        conda install -n base conda-build -y
        conda build conda-recipe --output-folder build_artifacts

    - name: Create conda env
      run: conda create -n bit -y

    - name: Add local area as channel
      run: conda run -n bit conda config --add channels file://${PWD}/build_artifacts

    - name: Install package
      run: |
        conda run -n bit conda install bit -y
        conda run -n bit pip install -e . # the editable pip install is so test coverages make sense

    - name: Check installed version
      run: conda run -n bit bit -v


    - name: Debug mosdepth
      run: |
        uname -m
        which -a mosdepth || true
        conda run -n bit bash -c 'file $CONDA_PREFIX/bin/mosdepth; ls -l $CONDA_PREFIX/bin/mosdepth'
        conda run -n bit bash -c 'lipo -archs $CONDA_PREFIX/bin/mosdepth || true'
        conda run -n bit conda list mosdepth


    - name: Run pytest
      run: conda run -n bit pytest
