name: build-and-test

on:
  push:
  pull_request:

jobs:
  test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.10"
        architecture: "x86_64"
        auto-activate-base: true
        channels: conda-forge,bioconda
        channel-priority: strict
        auto-update-conda: true

    - name: Build conda package
      run: |
        conda install -n base conda-build -y
        conda build conda-recipe --output-folder build_artifacts

    - name: Create conda env
      run: |
        conda create -n bit python=3.10 -y

    - name: Install built package
      run: |
        PKG=$(ls build_artifacts/*/*.conda | head -n1)
        conda run -n bit conda install "$PKG" -y

    - name: Run pytest
      run: conda run -n bit pytest -v
