name: build-and-test

on:
  push:
  pull_request:

jobs:
  build-and-test:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}

    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.10"
        architecture: "x86_64"
        auto-activate: true
        channels: conda-forge,bioconda
        channel-priority: strict
        auto-update-conda: true

    - name: Build conda package
      run: |
        conda install -n base conda-build -y
        conda build conda-recipe --output-folder build_artifacts

    - name: Create conda env
      run: |
        conda create -n bit python=3.10 -y

    - name: Adding local area as channel
      run: |
        conda run -n bit conda config --add channels file://${PWD}/build_artifacts

    - name: Install built package
      run: |
        conda run -n bit conda install bit -y

    # the first part allows the package to be sourced from the local dir, which makes test coverages make sense
    - name: Run pytest
      run: |
        conda run -n bit conda develop .
        conda run -n bit pytest -v
